# Copyright 2020, 2021 Clément "carlodrift" Raynaud, Lucas "Lucas_Cdry" Cadiry and contributors
#
# This file is part of Skoice.
#
# Skoice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Skoice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Skoice.  If not, see <https://www.gnu.org/licenses/>.

name: Skoice
version: ${project.version}
main: net.clementraynaud.skoice.Skoice
api-version: 1.13
authors: [ carlodrift, Lucas_Cdry ]
description: Proximity Voice Chat in Minecraft using Discord
website: ${project.url}
commands:
  link:
    usage: /link [code]
    description: Command to link in Minecraft.
  unlink:
    usage: /unlink
    description: Will unlink the player who uses the command, if they are linked.
  configure:
    usage: /configure
    default: op
    description: Allows operators to configure their bot.
  token:
    usage: /token [token]
    default: op
    description: Allows operators to register their bot.